export const diseases = [
  { index: 878325, name: 'AIDS', displayName: 'AIDS', category: 0 },
  { index: 878169, name: 'Adenovirus', displayName: 'Adenovirus', category: 1 },
  { index: 878259, name: 'Amebiasis', displayName: 'Amebiasis', category: 6 },
  {
    index: 878209,
    name: 'Atypical mycobacteria',
    displayName: 'Atypical mycobacteria',
    category: 6,
  },
  {
    index: 877935,
    name: 'C. difficile (toxin-producing)',
    displayName: 'C. difficile',
    category: 3,
  },
  {
    index: 878252,
    name: 'C. pneumoniae',
    displayName: 'C. pneumoniae',
    category: 1,
  },
  {
    index: 878164,
    name: 'CPE carriership, E. cloacae',
    displayName: 'CPE carriership, E. cloacae',
    category: 6,
  },
  {
    index: 877958,
    name: 'CPE carriership, E. coli',
    displayName: 'CPE carriership, E. coli',
    category: 3,
  },
  {
    index: 878012,
    name: 'CPE carriership, K. pneumoniae',
    displayName: 'CPE carriership, K. pneumoniae',
    category: 1,
  },
  {
    index: 878135,
    name: 'Campylobacter',
    displayName: 'Campylobacter',
    category: 3,
  },
  {
    index: 877715,
    name: 'Chikungunya',
    displayName: 'Chikungunya',
    category: 1,
  },
  { index: 877768, name: 'Chlamydia', displayName: 'Chlamydia', category: 0 },
  {
    index: 878269,
    name: 'Cinderella disease',
    displayName: 'Measles',
    fi: 'Tuhkarokko',
    category: 2,
  },
  {
    index: 877943,
    name: 'Coronavirus SARS-CoV-2',
    displayName: 'Coronavirus SARS-CoV-2',
    category: 1,
  },
  {
    index: 877659,
    name: 'Coxsackie A virus',
    displayName: 'Coxsackie A',
    fi: 'Enterorokko',
    category: 2,
  },
  {
    index: 877648,
    name: 'Coxsackie B virus',
    displayName: 'Coxsackie B',
    category: 3,
  },
  {
    index: 878249,
    name: 'Cryptosporidiosis',
    displayName: 'Cryptosporidiosis',
    category: 3,
  },
  { index: 878367, name: 'Dengue', displayName: 'Dengue', category: 1 },
  {
    index: 877921,
    name: 'Diphtheria',
    displayName: 'Diphtheria',
    fi: 'Kurkkumätä',
    category: 6,
  },
  {
    index: 878114,
    name: 'EHEC',
    displayName: 'Enterohemorrhagic E. coli ',
    category: 3,
  },
  {
    index: 878175,
    name: 'ESBL blood/liquor, E.coli',
    displayName: 'ESBL blood/liquor, E.coli',
    category: 3,
  },
  {
    index: 877764,
    name: 'ESBL blood/liquor, K.pneumoniae',
    displayName: 'ESBL blood/liquor, K.pneumoniae',
    category: 1,
  },
  {
    index: 877792,
    name: 'ESBL-carriership, E.coli',
    displayName: 'ESBL-carriership, E.coli',
    category: 3,
  },
  {
    index: 878134,
    name: 'ESBL-carriership, K.pneumoniae',
    displayName: 'ESBL-carriership, K.pneumoniae',
    category: 1,
  },
  {
    index: 878349,
    name: 'Echinococcus',
    displayName: 'Echinococcosis',
    category: 6,
  },
  { index: 877750, name: 'Echovirus', displayName: 'Echovirus', category: 6 },
  {
    index: 877821,
    name: 'Enterovirus',
    displayName: 'Enterovirus',
    category: 6,
  },
  {
    index: 877982,
    name: 'German measles',
    displayName: 'Rubella',
    fi: 'Vihurirokko',
    category: 2,
  },
  { index: 877839, name: 'Giardiasis', displayName: 'Giardiasis', category: 3 },
  {
    index: 877812,
    name: 'Gonorrhea',
    displayName: 'Gonorrhea',
    fi: 'Tippuri',
    category: 0,
  },
  {
    index: 877976,
    name: 'HIV, not AIDS',
    displayName: 'HIV, not AIDS',
    category: 0,
  },
  { index: 877747, name: 'HIV, total', displayName: 'HIV, total', category: 0 },
  {
    index: 878268,
    name: 'Haemophilus influenzae non-caps',
    displayName: 'Haemophilus influenzae non-caps',
    category: 1,
  },
  {
    index: 878031,
    name: 'Haemophilus influenzae type A',
    displayName: 'Haemophilus influenzae type A',
    category: 1,
  },
  {
    index: 878163,
    name: 'Haemophilus influenzae type B',
    displayName: 'Haemophilus influenzae type B',
    category: 1,
  },
  {
    index: 878348,
    name: 'Haemophilus influenzae type E',
    displayName: 'Haemophilus influenzae type E',
    category: 1,
  },
  {
    index: 877794,
    name: 'Haemophilus influenzae type F',
    displayName: 'Haemophilus influenzae type F',
    category: 1,
  },
  {
    index: 877696,
    name: 'Haemophilus influenzae, other',
    displayName: 'Haemophilus influenzae, other',
    category: 1,
  },
  {
    index: 877722,
    name: 'Haemophilus influenzae, total',
    displayName: 'Haemophilus influenzae, total',
    category: 1,
  },
  {
    index: 877759,
    name: 'Hepatitis A',
    displayName: 'Hepatitis A',
    category: 3,
  },
  {
    index: 877928,
    name: 'Hepatitis B, acute',
    displayName: 'Hepatitis B, acute',
    category: 0,
  },
  {
    index: 877829,
    name: 'Hepatitis B, chronic',
    displayName: 'Hepatitis B, chronic',
    category: 0,
  },
  {
    index: 878235,
    name: 'Hepatitis C',
    displayName: 'Hepatitis C',
    category: 6,
  },
  {
    index: 877949,
    name: 'Hepatitis D',
    displayName: 'Hepatitis D',
    category: 6,
  },
  {
    index: 878035,
    name: 'Hepatitis E',
    displayName: 'Hepatitis E',
    category: 6,
  },
  { index: 877719, name: 'Influenza', displayName: 'Influenza', category: 1 },
  {
    index: 877942,
    name: 'Influenza A',
    displayName: 'Influenza A',
    category: 1,
  },
  {
    index: 877733,
    name: 'Influenza B',
    displayName: 'Influenza B',
    category: 1,
  },
  {
    index: 878166,
    name: 'Legionellosis',
    displayName: 'Legionellosis',
    category: 1,
  },
  { index: 877890, name: 'Listeria', displayName: 'Listeriosis', category: 5 },
  {
    index: 878234,
    name: 'Lyme borreliosis',
    displayName: 'Lyme disease',
    fi: 'Borrelioosi',
    category: 6,
  },
  { index: 878155, name: 'MRSA carriership', displayName: 'MRSA', category: 3 },
  { index: 877668, name: 'Malaria', displayName: 'Malaria', category: 6 },
  {
    index: 878194,
    name: 'Meningococcus, NGA',
    displayName: 'Meningococcus, NGA',
    category: 5,
  },
  {
    index: 878021,
    name: 'Meningococcus, serogroup B',
    displayName: 'Meningococcus, serogroup B',
    category: 5,
  },
  {
    index: 877964,
    name: 'Meningococcus, serogroup C',
    displayName: 'Meningococcus, serogroup C',
    category: 5,
  },
  {
    index: 877691,
    name: 'Meningococcus, serogroup W',
    displayName: 'Meningococcus, serogroup W',
    category: 5,
  },
  {
    index: 878185,
    name: 'Meningococcus, serogroup Y',
    displayName: 'Meningococcus, serogroup Y',
    category: 5,
  },
  {
    index: 878327,
    name: 'Meningococcus, serogroup not known',
    displayName: 'Meningococcus, unknown serogroup',
    category: 5,
  },
  {
    index: 878192,
    name: 'Meningococcus, total',
    displayName: 'Meningococcus, total',
    category: 5,
  },
  { index: 878195, name: 'Mycoplasma', displayName: 'Mycoplasma', category: 6 },
  { index: 877752, name: 'Norovirus', displayName: 'Norovirus', category: 3 },
  {
    index: 878158,
    name: 'Parainfluenza virus',
    displayName: 'Parainfluenza',
    category: 1,
  },
  {
    index: 877932,
    name: 'Parvovirus',
    displayName: 'Parvovirus',
    fi: 'Parvorokko',
    category: 2,
  },
  {
    index: 878285,
    name: 'Pertussis',
    displayName: 'Whooping cough',
    fi: 'Hinkuyskä',
    category: 1,
  },
  {
    index: 878321,
    name: 'Pneumocystis',
    displayName: 'Pneumocystis pneumonia',
    category: 1,
  },
  {
    index: 878078,
    name: 'Pogostan disease',
    displayName: 'Pogostan disease',
    fi: 'Nivelrokko',
    category: 2,
  },
  { index: 877845, name: 'Polio', displayName: 'Polio', category: 6 },
  {
    index: 877858,
    name: 'Pulmonary tuberculosis',
    displayName: 'Pulmonary tuberculosis',
    category: 1,
  },
  {
    index: 877795,
    name: 'Puumala-virus',
    displayName: 'Puumalavirus',
    fi: 'Myyräkuume',
    category: 6,
  },
  { index: 877997, name: 'RSV', displayName: 'RSV', category: 1 },
  { index: 878243, name: 'Rotavirus', displayName: 'Rotavirus', category: 3 },
  {
    index: 878105,
    name: 'S. aureus, blood/liquor MRSA',
    displayName: 'S. aureus, blood/liquor MRSA',
    category: 3,
  },
  {
    index: 878263,
    name: 'S. aureus, blood/liquor not MRSA',
    displayName: 'S. aureus, blood/liquor not MRSA',
    category: 3,
  },
  {
    index: 878301,
    name: 'Salmonella Paratyphi',
    displayName: 'Salmonella Paratyphi',
    category: 3,
  },
  {
    index: 878372,
    name: 'Salmonella Typhi',
    displayName: 'Salmonella Typhi',
    category: 3,
  },
  {
    index: 877941,
    name: 'Salmonella, other',
    displayName: 'Salmonella, other',
    category: 3,
  },
  { index: 878138, name: 'Shigella', displayName: 'Shigella', category: 3 },
  {
    index: 878191,
    name: 'Streptococcus pneumoniae',
    displayName: 'Streptococcus pneumoniae',
    category: 1,
  },
  {
    index: 877647,
    name: 'Streptococcus A (S. pyogenes)',
    displayName: 'Streptococcus A (S. pyogenes)',
    category: 6,
  },
  {
    index: 878129,
    name: 'Streptococcus B (S. agalactiae)',
    displayName: 'Streptococcus B (S. agalactiae)',
    category: 6,
  },
  {
    index: 878051,
    name: 'Swine fever',
    displayName: 'Mumps',
    fi: 'Sikotauti',
    category: 6,
  },
  {
    index: 877778,
    name: 'Syphilis',
    displayName: 'Syphilis',
    fi: 'Kuppa',
    category: 0,
  },
  {
    index: 877823,
    name: 'TBE (tick borne encephalitis)',
    displayName: 'TBE (tick borne encephalitis)',
    fi: 'Puutiaisaivotulehdus',
    category: 6,
  },
  {
    index: 877744,
    name: 'Tuberculosis of other organs',
    displayName: 'Tuberculosis of other organs',
    category: 1,
  },
  {
    index: 878093,
    name: 'Tuberculosis, total',
    displayName: 'Tuberculosis, total',
    category: 1,
  },
  {
    index: 878173,
    name: 'Tularaemia (rabbit fever)',
    displayName: 'Tularaemia (rabbit fever)',
    fi: 'Jänisrutto',
    category: 6,
  },
  {
    index: 877916,
    name: 'VRE blood/liquor',
    displayName: 'VRE blood/liquor',
    category: 5,
  },
  {
    index: 878111,
    name: 'VRE carriership',
    displayName: 'VRE carriership',
    category: 5,
  },
  {
    index: 878256,
    name: 'Varicella zoster virus',
    displayName: 'Chickenpox',
    fi: 'Vesirokko',
    category: 2,
  },
  {
    index: 877807,
    name: 'Yersinia enterocolitica',
    displayName: 'Yersinia enterocolitica',
    category: 6,
  },
  {
    index: 877771,
    name: 'Yersinia pseudotuberculosis',
    displayName: 'Yersinia pseudotuberculosis',
    category: 6,
  },
  {
    index: 878362,
    name: 'Yersinia, other',
    displayName: 'Yersinia, other',
    category: 6,
  },
  {
    index: 877725,
    name: 'Yersinia, total',
    displayName: 'Yersinia, total',
    category: 6,
  },
  { index: 877665, name: 'Zika virus', displayName: 'Zika fever', category: 1 },
];

export const findDiseaseByIndex = index => {
  return diseases.find(d => d.index === index);
};

export const diseaseCategories = [
  { id: 1, name: 'Respiratory infections and tuberculosis' },
  { id: 2, name: 'Pox diseases' },
  { id: 3, name: 'Diarrhoeal diseases' },
  { id: 0, name: 'Sexually transmitted diseases' },
  { id: 5, name: 'Meningitis' },
  { id: 6, name: 'Other' },
];

export const diseasesByCategory = () => {
  const categories = [{ id: 7, name: 'All diseases' }, ...diseaseCategories];
  categories.forEach(c => {
    c.diseases = diseases.filter(d => d.category === c.id);
  });
  categories[0].diseases = diseases;
  return categories;
};
